name: pomly
description: Local-first study focus companion.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  cupertino_icons: ^1.0.8
  file_picker: ^8.1.7
  syncfusion_flutter_pdf: ^28.2.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
